Rebasing nightly to alpine 3.17
linuxserver/docker-thelounge pull request #52
Opened 2022-12-18 17:43 UTC by nemchik

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-thelounge/blob/nightly/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

## Benefits of this PR and context:

## How Has This Been Tested?

## Source / References:

2022-12-19 15:45 UTC, thespad commented on root/etc/s6-overlay/s6-rc.d/svc-thelounge/run
> +    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9000" \
Missing the corresponding `notification-fd` file for the readinesss check.

2022-12-21 13:55 UTC, thespad approved these changes

2022-12-21 13:58 UTC, thespad requested changes
Is the CI screenshot correct? It looks like it's expecting a username/password whereas next/master show the connection setup screen?

2022-12-21 20:30 UTC, nemchik commented
> Is the CI screenshot correct? It looks like it's expecting a username/password whereas next/master show the connection setup screen?

Fixed in https://github.com/linuxserver/docker-thelounge/pull/52/commits/a89e0ecab6034f08ba300a195fde53e07e61bf41

Similar commit applied to https://github.com/linuxserver/docker-thelounge/pull/50 and https://github.com/linuxserver/docker-thelounge/pull/51

2022-12-21 20:51 UTC, thespad approved these changes

2022-12-21 21:04 UTC, merged